services:
  tareas_app:
    container_name: tareas_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://proyecto_final_db:5432/proyectofinal
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - proyecto_final_db
    working_dir: /app
    command: mvn spring-boot:run
  proyecto_final_db:
    container_name: proyecto_final_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proyectofinal
  tareas_test:
    container_name: tareas_test
    image: maven:3.8.4-openjdk-17-slim
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - proyecto_final_db
    command: mvn test